{
 "title": "AWS RDS Overview",
 "tags": [
  "aws",
  "rds"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   { "name": "region", "query": "regions()" },
   {
    "name": "dbinstance",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": [ "$dbinstance" ] },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": [ "$dbinstance" ] },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": [ "$dbinstance" ] },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": [ "$dbinstance" ] },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "Read IOPS",
     "dimensions": { "DBInstanceIdentifier": [ "$dbinstance" ] },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Write IOPS",
     "dimensions": { "DBInstanceIdentifier": [ "$dbinstance" ] },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}